import sys
import numpy as np
import pyqcstrc.qnnum.qnnum as qnn
import pyqcstrc.qnvec.qnvec as qnv
import pyqcstrc.qnmat.qnmat as qnm
#import pyqcstrc.qnclass.qnmath

class Qnsym_Octa:
    def __init__(self):
        M0=qnn.Qnnum(np.array([ 0, 0, 1]),2) #  0
        M1=qnn.Qnnum(np.array([ 1, 0, 2]),2) #  1/2
        M2=qnn.Qnnum(np.array([ 0, 1, 2]),2) #  t=sqrt(2)/2
        M3=qnn.Qnnum(np.array([ 0,-1, 2]),2) # -t
        M4=qnn.Qnnum(np.array([-1,-1, 1]),2) # -1
        N=np.int64(2)
        n=np.int64(6)
        MT=np.array([
            [M2,M2,M0,M0,M0,M0], #
            [M3,M1,M3,M0,M0,M0], #
            [M0,M0,M0,M0,M0,M0], #
            [M0,M0,M0,M3,M2,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) #
        smo8=qnm.Qnmat(MT,n,N) # matrix of qnnum (qnmat)
        self.shape = MT.shape  #dimension of a vector a
        self.ndim = MT.ndim
        qnm.printqnm("Qnsym_Octa",smo8)  # for test
        # generate all symmetry operators generated by MT
        MTM=np.array([  # this may be incorrect
            [M4,M0,M0,M0,M0,M0], # 
            [M0,M4,M0,M0,M0,M0], # 
            [M0,M0,M4,M0,M0,M0], # 
            [M0,M0,M0,M4,M0,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) # 
        smom=qnm.Qnmat(MTM,n,N)
        qnm.printqnm("Qnsym_Octa",smom)  # for test
        # generate all symmetry operators generated by MT
        order=np.int64(8)
        self.smo=np.array(16,dtype=qnm.Qnmat)
        smo[0]=qnm.unitm(n,N)  # this should be the unit matrix
        for i in range(order-1):
            qnm.printqnm("smo[i]",smo[i])  # for test
            smo[i+1]=smo8@smo[i]
        
        # add mirror plane
        #for i in range(1):
        #    smo[i+12]=smom@smo[i-12]
        #self.order=order*2

# for decagonal QCs
class Qnsym_Deca:
    # note that this use orthorhombic coordinate system
    def __init__(self):
        M0=qnn.Qnnum(np.array([ 0, 0, 1]),5) #  0
        M1=qnn.Qnnum(np.array([ 1, 0, 1]),5) #  1
        M2=qnn.Qnnum(np.array([-1, 1, 2]),5) #  (-1+sqrt(5))/2 = tau^{-1} = mu/2
        M3=qnn.Qnnum(np.array([-5,-1, 2]),5) #  (-5-sqrt(5))/2 = -s/2
        M4=qnn.Qnnum(np.array([ 0,-1, 2]),5) #  -sqrt(5)/2 = -t/2
        M5=qnn.Qnnum(np.array([ 1, 1, 1]),5) #  (1+sqrt(5))/2 = tau/2
        M6=qnn.Qnnum(np.array([-1,-1, 1]),5) #  (-1-sqrt(5))/2 = -tau/2
        MT5=np.array([
            [M2,M1,M0,M0,M0,M0], #
            [M3,M2,M0,M0,M0,M0], #
            [M0,M0,M6,M2,M0,M0], # 
            [M0,M0,M4,M6,M0,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) # 
        smo5=qnm.Qnmat(MT5) # matrix of qnnum (qnmat)
        self.shape = MT5.shape  #dimension of a vector a
        self.ndim = MT5.ndim
        # generate all symmetry operators generated by MT
        MT2=np.array([  # this may be incorrect
            [M6,M0,M0,M0,M0,M0], # 
            [M0,M6,M0,M0,M0,M0], # 
            [M0,M0,M6,M0,M0,M0], # 
            [M0,M0,M0,M6,M0,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) # 
        smo2=qnm.Qnmat(MT2)
        # generate all symmetry operators generated by MT
        order=np.int64(20)
        self.smo=np.array(20,dtype=qnm.Qnmat)
        smo[0]=smo1 # this should be the unit matrix
        for i in range(order-1):
            smo[i+1]=smo5@smo[i]
        # add mirror plane
        for i in range(1):
            smo[i+5]=smo2@smo[i-6]
        self.order=order*2
# for dodecagonal QCs
class Qnsym_Dode:
    def __init__(self):
        """projection of a 6d vector onto Epar and Eperp in "SIN-style"
        NOTE: coefficient (alpha) of the projection matrix is set to be 1.
        alpha = 2*a/np.sqrt(6)
        see Yamamoto ActaCrystal (1997)
        """
        M0=qnn.Qnnum(np.array([ 0, 0, 1]),3)  # 0
        M1=qnn.Qnnum(np.array([ 1, 0, 1]),3)  # 1
        M2=qnn.Qnnum(np.array([ 1, 0, 2]),3)  # 1/2
        M3=qnn.Qnnum(np.array([-1, 0, 2]),3)  #-1/2
        M4=qnn.Qnnum(np.array([ 0, 1, 2]),3)  # sqrt(3)/2 = t/2 
        M5=qnn.Qnnum(np.array([ 0,-1, 2]),3) # -sqrt(3)/2 =-t/2
        M6=qnn.Qnnum(np.array([-1, 0, 1]),3)  # -1
        #M6=qnn.Qnnum(np.array([ 0,-1, 2]),3) # -sqrt(3)/2
        #M5=np.array([ 0, 1, 1]) # sqrt(3)
        #M6=np.array([ 0,-1, 1]) # -sqrt(3)
        MT12=np.array([
            [M4,M1,M0,M0,M0,M0], # 
            [M3,M4,M0,M0,M0,M0], # 
            [M0,M0,M5,M2,M0,M0], # 
            [M0,M0,M3,M5,M0,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) # 
        smo12=qnm.Qnmat(MT12) # matrix of qnnum (qnmat)
        self.shape = MT12.shape  #dimension of a vector a
        self.ndim = MT12.ndim
        MTM=np.array([  # this may be incorrect
            [M6,M0,M0,M0,M0,M0], # 
            [M0,M6,M0,M0,M0,M0], # 
            [M0,M0,M6,M0,M0,M0], # 
            [M0,M0,M0,M6,M0,M0], #
            [M0,M0,M0,M0,M1,M0], #
            [M0,M0,M0,M0,M0,M1]]) # 
        smom=qnm.Qnmat(MTM)
        # generate all symmetry operators generated by MT
        order=np.int64(12)
        self.smo=np.array(24,dtype=qnm.Qnmat)
        smo[0]=smo1  # this should be the unit matrix
        for i in range(order-1):
            smo[i+1]=smo12@smo[i]
        # add mirror plane
        #for i in range(1):
        #    smo[i+12]=smom@smo[i-12]
        #self.order=order*2

if __name__ == '__main__':
    # test for qnnum projection operators
    
    a=Qnsym_Octa()
    la=a.order
    print("la",la)
    print("Octa.a")
    for i in range(la):
        qnm.printqnm("Qnsym_Octa",a.smo[i])

