{'includes': [{'filename': '<array>'}, {'filename': '<numeric>'},
              {'filename': '<cmath>'}, {'filename': '<iostream>'},
              {'filename': '"crsys.hpp"'}],
 'namespace': {'classes': [],
               'concepts': [],
               'deduction_guides': [],
               'doxygen': None,
               'enums': [],
               'forward_decls': [],
               'functions': [],
               'inline': False,
               'method_impls': [],
               'name': '',
               'namespaces': {'qnnum': {'classes': [{'class_decl': {'access': None,
                                                                    'bases': [],
                                                                    'doxygen': None,
                                                                    'explicit': False,
                                                                    'final': False,
                                                                    'template': None,
                                                                    'typename': {'classkey': 'class',
                                                                                 'has_typename': False,
                                                                                 'segments': [{'name': 'Qnnum',
                                                                                               'specialization': None}]}},
                                                     'classes': [],
                                                     'enums': [],
                                                     'fields': [{'access': 'public',
                                                                 'bits': None,
                                                                 'constexpr': False,
                                                                 'doxygen': None,
                                                                 'inline': False,
                                                                 'mutable': False,
                                                                 'name': 'n',
                                                                 'static': False,
                                                                 'type': {'array_of': {'const': False,
                                                                                       'typename': {'classkey': None,
                                                                                                    'has_typename': False,
                                                                                                    'segments': [{'name': 'int'}]},
                                                                                       'volatile': False},
                                                                          'size': {'tokens': [{'type': 'INT_CONST_DEC',
                                                                                               'value': '3'}]}},
                                                                 'value': None}],
                                                     'forward_decls': [],
                                                     'friends': [],
                                                     'methods': [{'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'signm',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': None,
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'a',
                                                                                  'param_pack': False,
                                                                                  'type': {'const': False,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'int'}]},
                                                                                           'volatile': False}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'int'}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': True,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'Qnnum',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': None,
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'n_',
                                                                                  'param_pack': False,
                                                                                  'type': {'array_of': {'const': False,
                                                                                                        'typename': {'classkey': None,
                                                                                                                     'has_typename': False,
                                                                                                                     'segments': [{'name': 'int'}]},
                                                                                                        'volatile': False},
                                                                                           'size': None}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': None,
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator+',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '+',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator-',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '-',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator+=',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '+=',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator-=',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '-=',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator*',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '*',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator*',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '*',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'const': True,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'int'}]},
                                                                                           'volatile': False}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator/',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '/',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator/',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '/',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'const': False,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'int'}]},
                                                                                           'volatile': False}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator==',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '==',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'bool'}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator<',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '<',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'bool'}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator>',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '>',
                                                                  'override': False,
                                                                  'parameters': [{'default': None,
                                                                                  'name': 'b',
                                                                                  'param_pack': False,
                                                                                  'type': {'ref_to': {'const': False,
                                                                                                      'typename': {'classkey': None,
                                                                                                                   'has_typename': False,
                                                                                                                   'segments': [{'name': 'Qnnum',
                                                                                                                                 'specialization': None}]},
                                                                                                      'volatile': False}}}],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'bool'}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False},
                                                                 {'access': 'public',
                                                                  'const': False,
                                                                  'constexpr': False,
                                                                  'constructor': False,
                                                                  'default': False,
                                                                  'deleted': False,
                                                                  'destructor': False,
                                                                  'doxygen': None,
                                                                  'explicit': False,
                                                                  'extern': False,
                                                                  'final': False,
                                                                  'has_body': True,
                                                                  'has_trailing_return': False,
                                                                  'inline': False,
                                                                  'msvc_convention': None,
                                                                  'name': {'classkey': None,
                                                                           'has_typename': False,
                                                                           'segments': [{'name': 'operator-',
                                                                                         'specialization': None}]},
                                                                  'noexcept': None,
                                                                  'operator': '-',
                                                                  'override': False,
                                                                  'parameters': [],
                                                                  'pure_virtual': False,
                                                                  'raw_requires': None,
                                                                  'ref_qualifier': None,
                                                                  'return_type': {'const': False,
                                                                                  'typename': {'classkey': None,
                                                                                               'has_typename': False,
                                                                                               'segments': [{'name': 'Qnnum',
                                                                                                             'specialization': None}]},
                                                                                  'volatile': False},
                                                                  'static': False,
                                                                  'template': None,
                                                                  'throw': None,
                                                                  'vararg': False,
                                                                  'virtual': False,
                                                                  'volatile': False}],
                                                     'typedefs': [],
                                                     'using': [],
                                                     'using_alias': []}],
                                        'concepts': [],
                                        'deduction_guides': [],
                                        'doxygen': None,
                                        'enums': [],
                                        'forward_decls': [],
                                        'functions': [{'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'init',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'void'}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'zero',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'Qnnum',
                                                                                                  'specialization': None}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'one',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'Qnnum',
                                                                                                  'specialization': None}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'any',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'n_',
                                                                       'param_pack': False,
                                                                       'type': {'array_of': {'const': False,
                                                                                             'typename': {'classkey': None,
                                                                                                          'has_typename': False,
                                                                                                          'segments': [{'name': 'int'}]},
                                                                                             'volatile': False},
                                                                                'size': None}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'Qnnum',
                                                                                                  'specialization': None}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'qn2flt',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'a',
                                                                       'param_pack': False,
                                                                       'type': {'ref_to': {'const': False,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'Qnnum',
                                                                                                                      'specialization': None}]},
                                                                                           'volatile': False}}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'double'}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'int2qn',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'i',
                                                                       'param_pack': False,
                                                                       'type': {'const': False,
                                                                                'typename': {'classkey': None,
                                                                                             'has_typename': False,
                                                                                             'segments': [{'name': 'int'}]},
                                                                                'volatile': False}},
                                                                      {'default': None,
                                                                       'name': 'N',
                                                                       'param_pack': False,
                                                                       'type': {'const': False,
                                                                                'typename': {'classkey': None,
                                                                                             'has_typename': False,
                                                                                             'segments': [{'name': 'int'}]},
                                                                                'volatile': False}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'Qnnum',
                                                                                                  'specialization': None}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'flt2qn',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'qr',
                                                                       'param_pack': False,
                                                                       'type': {'const': False,
                                                                                'typename': {'classkey': None,
                                                                                             'has_typename': False,
                                                                                             'segments': [{'name': 'float'}]},
                                                                                'volatile': False}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'Qnnum',
                                                                                                  'specialization': None}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'printqnn',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'str',
                                                                       'param_pack': False,
                                                                       'type': {'ref_to': {'const': True,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'string',
                                                                                                                      'specialization': None}]},
                                                                                           'volatile': False}}},
                                                                      {'default': None,
                                                                       'name': 'a',
                                                                       'param_pack': False,
                                                                       'type': {'ref_to': {'const': False,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'Qnnum',
                                                                                                                      'specialization': None}]},
                                                                                           'volatile': False}}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'void'}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False},
                                                      {'constexpr': False,
                                                       'deleted': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'has_body': True,
                                                       'has_trailing_return': False,
                                                       'inline': False,
                                                       'msvc_convention': None,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'printqnns',
                                                                              'specialization': None}]},
                                                       'noexcept': None,
                                                       'operator': None,
                                                       'parameters': [{'default': None,
                                                                       'name': 'str',
                                                                       'param_pack': False,
                                                                       'type': {'ref_to': {'const': True,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'string',
                                                                                                                      'specialization': None}]},
                                                                                           'volatile': False}}},
                                                                      {'default': None,
                                                                       'name': 'a',
                                                                       'param_pack': False,
                                                                       'type': {'ref_to': {'const': False,
                                                                                           'typename': {'classkey': None,
                                                                                                        'has_typename': False,
                                                                                                        'segments': [{'name': 'vector',
                                                                                                                      'specialization': {'args': [{'arg': {'const': False,
                                                                                                                                                           'typename': {'classkey': None,
                                                                                                                                                                        'has_typename': False,
                                                                                                                                                                        'segments': [{'name': 'Qnnum',
                                                                                                                                                                                      'specialization': None}]},
                                                                                                                                                           'volatile': False},
                                                                                                                                                   'param_pack': False}]}}]},
                                                                                           'volatile': False}}}],
                                                       'raw_requires': None,
                                                       'return_type': {'const': False,
                                                                       'typename': {'classkey': None,
                                                                                    'has_typename': False,
                                                                                    'segments': [{'name': 'void'}]},
                                                                       'volatile': False},
                                                       'static': False,
                                                       'template': None,
                                                       'throw': None,
                                                       'vararg': False}],
                                        'inline': False,
                                        'method_impls': [],
                                        'name': 'qnnum',
                                        'namespaces': {},
                                        'ns_alias': [],
                                        'template_insts': [],
                                        'typedefs': [],
                                        'using': [],
                                        'using_alias': [],
                                        'using_ns': [],
                                        'variables': [{'constexpr': False,
                                                       'doxygen': None,
                                                       'extern': False,
                                                       'inline': False,
                                                       'name': {'classkey': None,
                                                                'has_typename': False,
                                                                'segments': [{'name': 'N',
                                                                              'specialization': None}]},
                                                       'static': False,
                                                       'template': None,
                                                       'type': {'const': False,
                                                                'typename': {'classkey': None,
                                                                             'has_typename': False,
                                                                             'segments': [{'name': 'int'}]},
                                                                'volatile': False},
                                                       'value': None}]}},
               'ns_alias': [],
               'template_insts': [],
               'typedefs': [],
               'using': [],
               'using_alias': [],
               'using_ns': [{'ns': 'std'}],
               'variables': []},
 'pragmas': [{'content': {'tokens': [{'type': 'NAME', 'value': 'once'}]}}]}
